# Generated by Django 4.0 on 2022-01-04 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='likes',
            field=models.ManyToManyField(related_name='house', to=settings.AUTH_USER_MODEL),
        ),
    ]
